name: Bejoo
description: Joris Morger, Nicolas Gagliani
meta_description: "Bejoo and programming"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Joris Morger, Nicolas Gagliani'
